### ISSUE TITLE
[BUG]post_url心跳报错

### ISSUE THREAD

**Issue by yimo0908** [yyuueexxiinngg/onebot-kotlin#113]
post_url心跳报错

```
2020-11-23 22:45:08 E/OneBot: Exception in Heartbeat
io.ktor.network.sockets.SocketTimeoutException: Socket timeout has been expired [url=http://tataru.aoba.vip/api/cq_http_api.php?key=044b1eae5afbe493a28ad77e18cdd785, socket_timeout=unknown] ms
        at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:189)
        at io.ktor.client.engine.okhttp.OkUtilsKt$execute$$inlined$suspendCancellableCoroutine$lambda$1.onFailure(OkUtils.kt:31)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:510)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: timeout
        at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
        at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        ... 3 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        ... 20 more
```

#### 复现
正常启动并连接后，过一段时间就会发生

#### 版本
onebot-`kotlin `- `0.3.2 `

**Comment by yimo0908** [comment]
问了一下post_url的上游提供者，post_url这种方式是不该有心跳的
![image](https://user-images.githubusercontent.com/53830825/100199251-e4026100-2f37-11eb-8681-c174d853e2d2.png)

**Comment by a08381** [comment]
> 问了一下post_url的上游提供者，post_url这种方式是不该有心跳的
> 
> ![image](https://user-images.githubusercontent.com/53830825/100199251-e4026100-2f37-11eb-8681-c174d853e2d2.png)
> 
> 

但是事实上onebot认为http也应该有心跳？毕竟这里没有说http没有

[元事件#心跳](https://github.com/howmanybots/onebot/blob/master/v11/specs/event/meta.md#心跳)

**Comment by yyuueexxiinngg** [comment]
已询问RC, 心跳是普通事件, 都有
