### ISSUE TITLE
[BUG]当前版本过低，请先升级到手机QQ最新版本

### ISSUE THREAD

**Issue by Ukenn2112** [yyuueexxiinngg/onebot-kotlin#122]
在执行login时出现该问题

```
Login failed: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
2020-12-16 23:42:28 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

#### 复现

在执行login时出现该问题

#### 版本
onebot-kotlin-0.3.3-

mirai-core-` `   

mirai-console-` `

**Comment by ckn4** [comment]
同样遇到这个问题，log另一位已给出

**Comment by a08381** [comment]
@Ukenn2112 @ckn4 这个问题是账号密码或者验证码错了一个。我没遇到过这个问题，不过群里别人提到过很多次

**Comment by ckn4** [comment]
上游好像有解决，今天发版。

https://github.com/mamoe/mirai/issues/621#issuecomment-747151918

**Comment by SnowMoonSS** [comment]
更新到最新版的mirai就行了

**Comment by Ukenn2112** [comment]
但更新最新版本后出现新的问题：
```Login failed: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
2020-12-22 22:06:40 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=为了您的帐 号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:185)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

目前基本确定是上游问题 https://github.com/mamoe/mirai/issues/717#issue-768437268
等待上游恢复，此issue关闭
