### ISSUE TITLE
跟进mirai 2.0更新

### ISSUE THREAD

**Issue by yyuueexxiinngg** [yyuueexxiinngg/onebot-kotlin#124]
`mirai`2.0重构已在2.0-M2版本趋于稳定, 开始进行适配

- [x] 跟进2.0-M-2
- [x] 跟进2.0-RC

**Comment by a08381** [comment]
如果大佬有兴趣的话可以看一下我的fork（不会kotlin，按照Java习惯来边猜边写的渣代码，就不pr了）

**Comment by yyuueexxiinngg** [comment]
https://github.com/yyuueexxiinngg/onebot-kotlin/runs/1636609722

已更新, 不过没时间进行更多测试......

**Comment by ckn4** [comment]
你好，使用适配M2的最新kotlin版会报错，是否应该切换桌面版协议

2021-01-04 11:26:08 E/console: net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试
net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:199)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by ckn4** [comment]
> 你好，使用适配M2的最新kotlin版会报错，是否应该切换桌面版协议
> 
> 2021-01-04 11:26:08 E/console: net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试
> net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试
> at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:199)
> at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
> at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

通过更换协议为WATCH已解决
