### ISSUE TITLE
[Question] Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请 更换协议后重试

### ISSUE THREAD

**Issue by KagamiMiro** [yyuueexxiinngg/onebot-kotlin#140]
刚刚手里的一个账号好像因为，很多账号同时给那一个账号发相同的消息，导致被风控了。

换了一个新账号以后出现如下错误

2021-06-12 10:14:21 I/main: Starting mirai-console...
2021-06-12 10:14:21 I/main: Backend: version 2.0-RC, built on 2021-01-12 19:08:10.
2021-06-12 10:14:21 I/main: Frontend Terminal: version 2.0-RC, provided by Mamoe Technologies
2021-06-12 10:14:21 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-06-12 10:14:21 I/main: 0 plugin(s) enabled.
2021-06-12 10:14:21 I/main: mirai-console started successfully.
2021-06-12 10:14:21 I/OneBot: Plugin loaded! 0.3.4
2021-06-12 10:14:21 I/OneBot: 插件当前Commit 版本: 75a84ee
2021-06-12 10:14:21 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2021-06-12 10:14:21 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2021-06-12 10:14:22 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
2021-06-12 10:14:22 W/stderr:   at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
2021-06-12 10:14:22 W/stderr:   at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:230)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:57)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:161)
2021-06-12 10:14:22 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
2021-06-12 10:14:22 W/stderr:   at com.github.yyuueexxiinngg.onebot.MainKt$runMirai$1.invokeSuspend(Main.kt:91)
2021-06-12 10:14:22 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-06-12 10:14:22 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-06-12 10:14:22 W/stderr:   at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
2021-06-12 10:14:22 W/stderr:   at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
2021-06-12 10:14:22 W/stderr:   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
2021-06-12 10:14:22 W/stderr:   at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2021-06-12 10:14:22 W/stderr:   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
2021-06-12 10:14:22 W/stderr:   at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2021-06-12 10:14:22 W/stderr:   at com.github.yyuueexxiinngg.onebot.MainKt.runMirai(Main.kt:89)
2021-06-12 10:14:22 W/stderr:   at com.github.yyuueexxiinngg.onebot.OneBotKtCli.run(Main.kt:71)
2021-06-12 10:14:22 W/stderr:   at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:171)
2021-06-12 10:14:22 W/stderr:   at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
2021-06-12 10:14:22 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
2021-06-12 10:14:22 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2021-06-12 10:14:22 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2021-06-12 10:14:22 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2021-06-12 10:14:22 W/stderr:   at com.github.yyuueexxiinngg.onebot.MainKt.main(Main.kt:78)
2021-06-12 10:14:22 W/stderr: Caused by: java.util.jar.JarException: file:/D:/Program/oneBot2/onebot-kotlin-0.3.4-all.jar has unsigned entries - com/github/yyuueexxiinngg/onebot/MainKt.class
2021-06-12 10:14:22 W/stderr:   at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:510)
2021-06-12 10:14:22 W/stderr:   at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:371)
2021-06-12 10:14:22 W/stderr:   at javax.crypto.JarVerifier.verify(JarVerifier.java:297)
2021-06-12 10:14:22 W/stderr:   at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
2021-06-12 10:14:22 W/stderr:   at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
2021-06-12 10:14:22 W/stderr:   at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
2021-06-12 10:14:22 W/stderr:   ... 29 more
2021-06-12 10:14:22 I/Bot.2100141537: Logging in...
2021-06-12 10:14:23 W/stderr: Exception in thread "main" net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试
2021-06-12 10:14:23 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:202)
2021-06-12 10:14:23 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
2021-06-12 10:14:23 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
2021-06-12 10:14:23 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
2021-06-12 10:14:23 W/stderr:   at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2021-06-12 10:14:23 W/stderr:   at com.github.yyuueexxiinngg.onebot.MainKt.runMirai(Main.kt:89)
2021-06-12 10:14:23 W/stderr:   at com.github.yyuueexxiinngg.onebot.OneBotKtCli.run(Main.kt:71)
2021-06-12 10:14:23 W/stderr:   at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:171)
2021-06-12 10:14:23 W/stderr:   at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
2021-06-12 10:14:23 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
2021-06-12 10:14:23 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
2021-06-12 10:14:23 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
2021-06-12 10:14:23 W/stderr:   at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
2021-06-12 10:14:23 W/stderr:   at com.github.yyuueexxiinngg.onebot.MainKt.main(Main.kt:78)

**Comment by coderykw** [comment]
怎么解决得 换watch 提示版本过低

**Comment by NoverNobida** [comment]
为什么我通过更改` /config/Console/AutoLogin.yml `里面的协议，改成了watch或者pad，登录的时候还是提示`使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试`？这个更改了没起效果啊。
