### ISSUE TITLE
[Question]机器人私聊发送不了图片,群聊正常

### ISSUE THREAD

**Issue by zhouhuichen741** [yyuueexxiinngg/onebot-kotlin#141]
之前一直是好的,突然不能私聊回复图片了,文字之类的一切正常,群聊图片也一直正常发送,报错如下:
`2021-06-18 13:20:40 D/OneBot: 发生了被插件忽略的事件: BeforeImageUploadEvent(target=Friend(回复的QQ号), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@f07192)
2021-06-18 13:20:40 D/OneBot: 发生了被插件忽略的事件: Failed(target=Friend(回复的QQ), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@f07192, errno=-1, message=para error)
2021-06-18 13:20:40 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
java.lang.IllegalStateException: para error
  at net.mamoe.mirai.internal.contact.AbstractUser.uploadImage$suspendImpl(AbstractUser.kt:136)
  at net.mamoe.mirai.internal.contact.AbstractUser$uploadImage$1.invokeSuspend(AbstractUser.kt)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`
版本
onebot-mirai-0.3.4

mirai-core-2.2.0

mirai-console-2.2.0

**Comment by yyuueexxiinngg** [comment]
> 2021-06-18 13:20:40 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative

`MiraiNative`的错误?

**Comment by zhouhuichen741** [comment]
> > 2021-06-18 13:20:40 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
> 
> `MiraiNative`的错误?

不太清楚,我去MiraiNative那边也提交一个问题报告看看

**Comment by zhouhuichen741** [comment]
尝试过更新mirai版本,更换服务器等操作,报错的情况是一样的,上个月都是正常运行的,也可以私聊发图之类的,所以完全搞不明白是哪个地方出现了问题

**Comment by zhouhuichen741** [comment]
应该是隔壁native需要更新了,有一位大佬接手了这个问题,非常感谢[https://github.com/iTXTech/mirai-native/issues/142](url)
