### ISSUE TITLE
[Question]机器人发送图片缓存问题

### ISSUE THREAD

**Issue by zhouhuichen741** [yyuueexxiinngg/onebot-kotlin#143]
第一次发送正常,第二次发送无法发送报错

2021-07-02 18:21:20 I/OneBot: 此链接图片已缓存, 如需删除缓存请至 E:\MIRAI2.2\data\OneBot\image\789D3CC444DA9195CF91A564BD630C5C.cqimg
2021-07-02 18:21:20 W/stderr: Exception in thread "DefaultDispatcher-worker-8" java.lang.NoClassDefFoundError: Could not initialize class com.github.yyuueexxiinngg.onebot.util.ImgUtil
2021-07-02 18:21:20 W/stderr:   at com.github.yyuueexxiinngg.onebot.util.CQMessgeParserKt.tryResolveCachedImage(CQMessgeParser.kt:578)
2021-07-02 18:21:20 W/stderr:   at com.github.yyuueexxiinngg.onebot.util.CQMessgeParserKt$tryResolveMedia$2.invokeSuspend(CQMessgeParser.kt:404)
2021-07-02 18:21:20 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-07-02 18:21:20 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-07-02 18:21:20 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-07-02 18:21:20 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2021-07-02 18:21:20 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-07-02 18:21:20 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

onbot版本:onebot-mirai-0.3.4-all

**Comment by zhouhuichen741** [comment]
更新了mirai2.6.4好了
