### ISSUE TITLE
[BUG] 发送图片报错 cannot upload group image

### ISSUE THREAD

**Issue by Yukinekoko** [yyuueexxiinngg/onebot-kotlin#87]
大概是两个星期前使用是一切正常的，最近出现部分图片无法发送的情况，当时使用的是老版本的cqhttp-mirai，之后尝试更新到了最新版本也还是会出现这样的情况。

控制台可以看到报错`java.io.FileNotFoundException: /tmp/tmp6394909033307286485.tmp (No such file or directory)`。但我查看发现这个文件是存在的。

```
这一部分是发送正常的
 14:58:36 [INFO] [BOT 1021565183] [1幽2防3攻4辅(576570340)] 我(754685421) -> [mirai:source:147977,853744114]官漫130
 14:58:36 [DEBUG] [CQHTTPMirai] {"action": "send_msg", "params": {"group_id": 576570340, "user_id": 754685421, "message_type": "group", "message": [{"type": "at", "data": {"qq": "754685421"}}, {"type": "text", "data": {"text": " \u30d7\u30ea\u30f3\u30bb\u30b9\u30b3\u30cd\u30af\u30c8\uff01Re:Dive\u516c\u5f0f4\u30b3\u30de\n\u7b2c130\u8a71 \u8033\u304b\u304d\u306e\u8155\u524d\n"}}, {"type": "image", "data": {"file": "http://pcr.yukineko.xyz/hoshinores/img/priconne/comic/episode_130.png"}}]}, "echo": {"seq": 66}}
 14:58:36 [ERROR] [CQHTTPMirai] Image B05A873ADC99DFD5EBE6AD90B932E1E1 cache file cannot be found.
 14:58:36 [INFO] [NETWORK] Send: ImgStore.GroupPicUp
 14:58:36 [INFO] [NETWORK] Recv: FileExists(fileId=2156450824, fileInfo=ImgInfo(fileMd5=[-79, 60, 2, -95, -4, 25, -65, -84, -90, -25, 99, -100, 1, 93, -60, -105], fileType=1000, fileSize=160276, fileWidth=0, fileHeight=0))
 14:58:36 [INFO] [CQHTTPMirai] 此链接图片将缓存为B05A873ADC99DFD5EBE6AD90B932E1E1.cqimg
 14:58:36 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 14:58:36 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.SUCCESS
 14:58:36 [INFO] [BOT 1021565183] Group(576570340) <- [mirai:at:754685421,@我] プリンセスコネクト！Re:Dive 公式4コマ\n第130話 耳かきの腕前\n[mirai:image:{B13C02A1-FC19-BFAC-A6E7-639C015DC497}.mirai]
 14:58:36 [DEBUG] [CQHTTPMirai] {"status":"ok","retcode":0,"data":{"ClassType":"MessageData","message_id":147978},"echo":{"seq":66}}


下面这一部分是发送报错的

  14:59:22 [INFO] [BOT 1021565183] [1幽2防3攻4辅(576570340)] 我(754685421) -> [mirai:source:147979,1595994571]官漫184
 14:59:22 [DEBUG] [CQHTTPMirai] {"action": "send_msg", "params": {"group_id": 576570340, "user_id": 754685421, "message_type": "group", "message": [{"type": "at", "data": {"qq": "754685421"}}, {"type": "text", "data": {"text": " \u30d7\u30ea\u30f3\u30bb\u30b9\u30b3\u30cd\u30af\u30c8\uff01Re:Dive\u516c\u5f0f4\u30b3\u30de\n\u7b2c184\u8a71 \u71c3\u3048\u3066\u30d5\u30a1\u30fc\u30de\u30fc\n"}}, {"type": "image", "data": {"file": "http://pcr.yukineko.xyz/hoshinores/img/priconne/comic/episode_184.png"}}]}, "echo": {"seq": 67}}
 14:59:22 [ERROR] [CQHTTPMirai] Image 5FC5B84459CFF4FFA59A70118CDE3A0E cache file cannot be found.
 14:59:23 [INFO] [NETWORK] Send: ImgStore.GroupPicUp
 14:59:23 [INFO] [NETWORK] Recv: RequireUpload(fileId=2685534104, uKey=[-98, -98, 7, 14, 83, 38, -63, 87, -98, 121, -116, 127, 113, 21, 76, 91, 111, 69, -96, -32, 8, 5, 37, 68, 79, -38, -128, 6, 34, -38, 30, -90, -128, 7, 119, -7, 85, -58, -24, 9, -118, 27, 46, -48, -14, 60, 3, 20, -91, 60, -77, -107, -78, 19, 74, -1, -8, 115, 35, 42, 48, 22, 31, 43, 85, 90, 9, -82, 61, -65, -65, -128, 39, 54, 7, -33, 94, 122, -70, 94, -45, -33, -80, -82, -35, -55, -98, 61, -121, 40, 61, 124, 43, 101, -30, 127, -25, 9, 75, -123, -23, 95, -82, -49, -64, -115, -68, 24, -50, 46, 85, -57, -15, -7, -89, -59, 11, 39, -34, -95, -30, -63, 97, -46, -37, -35, -35, -6])
 14:59:23 [INFO] [NETWORK] [Highway] Uploading group image to 182.254.57.124:80, size=248.73 KiB
 15:00:59 [INFO] [NETWORK] [Highway] Uploading group image to 203.205.234.15:8080, size=0 B
 15:00:59 [INFO] [NETWORK] [Highway] Uploading group image to 14.18.180.184:443, size=0 B
 15:00:59 [INFO] [NETWORK] [Highway] Uploading group image to 123.151.190.210:80, size=0 B
 15:00:59 [ERROR] [CQHTTPMirai] java.lang.IllegalStateException: cannot upload group image, failed on all servers.
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageToServers(HighwayHelper.kt:114)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageToServers(HighwayHelper.kt:99)
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.uploadImage(GroupImpl.kt:434)
        at net.mamoe.mirai.qqandroid.contact.GroupImpl$uploadImage$1.invokeSuspend(GroupImpl.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.FileNotFoundException: /tmp/tmp6890495935792386052.tmp (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
        at net.mamoe.mirai.utils.internal.AsReusableInput_jvmKt$asReusableInput$2.chunkedFlow(asReusableInput.jvm.kt:61)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput.chunkedFlow(DeferredReusableInput.jvm.kt:50)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayKt.createImageDataPacketSequence(highway.kt:45)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayKt.createImageDataPacketSequence$default(highway.kt:40)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImage$mirai_core_qqandroid(HighwayHelper.kt:163)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImageToServers$$inlined$retryWithServers$1.invokeSuspend(HighwayHelper.kt:283)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImageToServers$$inlined$retryWithServers$1.invoke(HighwayHelper.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:120)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:83)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageToServers(HighwayHelper.kt:273)
        ... 12 more

 15:00:59 [DEBUG] [CQHTTPMirai] {"status":"failed","retcode":103,"data":null,"echo":{"seq":67}}

```

#### 复现

目前只是我出现了这样的情况，不清楚能否复现

#### 版本
cqhttp-mirai- `0.2.3-embedded `

**Comment by yyuueexxiinngg** [comment]
应该与`mirai`本身有关

https://github.com/mamoe/mirai/issues/675
